//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoffDotNet.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoffDotNet.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_001 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_002 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_003 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_004 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_005 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_006 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_006", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_extraneous_data_007 {
            get {
                object obj = ResourceManager.GetObject("blocks_extraneous_data_007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_metadata_absent_001 {
            get {
                object obj = ResourceManager.GetObject("blocks_metadata_absent_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_metadata_absent_002 {
            get {
                object obj = ResourceManager.GetObject("blocks_metadata_absent_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_ordering_001 {
            get {
                object obj = ResourceManager.GetObject("blocks_ordering_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_ordering_002 {
            get {
                object obj = ResourceManager.GetObject("blocks_ordering_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_ordering_003 {
            get {
                object obj = ResourceManager.GetObject("blocks_ordering_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_ordering_004 {
            get {
                object obj = ResourceManager.GetObject("blocks_ordering_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_overlap_001 {
            get {
                object obj = ResourceManager.GetObject("blocks_overlap_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_overlap_002 {
            get {
                object obj = ResourceManager.GetObject("blocks_overlap_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_overlap_003 {
            get {
                object obj = ResourceManager.GetObject("blocks_overlap_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_private_001 {
            get {
                object obj = ResourceManager.GetObject("blocks_private_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_private_absent_001 {
            get {
                object obj = ResourceManager.GetObject("blocks_private_absent_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blocks_private_absent_002 {
            get {
                object obj = ResourceManager.GetObject("blocks_private_absent_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_4_byte_001 {
            get {
                object obj = ResourceManager.GetObject("directory_4_byte_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_4_byte_003 {
            get {
                object obj = ResourceManager.GetObject("directory_4_byte_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_ascending_001 {
            get {
                object obj = ResourceManager.GetObject("directory_ascending_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_compLength_001 {
            get {
                object obj = ResourceManager.GetObject("directory_compLength_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_extraneous_data_001 {
            get {
                object obj = ResourceManager.GetObject("directory_extraneous_data_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_origLength_001 {
            get {
                object obj = ResourceManager.GetObject("directory_origLength_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_origLength_002 {
            get {
                object obj = ResourceManager.GetObject("directory_origLength_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_overlaps_001 {
            get {
                object obj = ResourceManager.GetObject("directory_overlaps_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_overlaps_002 {
            get {
                object obj = ResourceManager.GetObject("directory_overlaps_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_overlaps_003 {
            get {
                object obj = ResourceManager.GetObject("directory_overlaps_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_overlaps_004 {
            get {
                object obj = ResourceManager.GetObject("directory_overlaps_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] directory_overlaps_005 {
            get {
                object obj = ResourceManager.GetObject("directory_overlaps_005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] header_numTables_001 {
            get {
                object obj = ResourceManager.GetObject("header_numTables_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] header_reserved_001 {
            get {
                object obj = ResourceManager.GetObject("header_reserved_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] header_signature_001 {
            get {
                object obj = ResourceManager.GetObject("header_signature_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] InvalidHeader_WrongMagicNumber {
            get {
                object obj = ResourceManager.GetObject("InvalidHeader_WrongMagicNumber", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] InvalidHeader_WrongReservedValue {
            get {
                object obj = ResourceManager.GetObject("InvalidHeader_WrongReservedValue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] InvalidHeader_WrongSfntSizeValue {
            get {
                object obj = ResourceManager.GetObject("InvalidHeader_WrongSfntSizeValue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_compression_001 {
            get {
                object obj = ResourceManager.GetObject("metadata_compression_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_encoding_001 {
            get {
                object obj = ResourceManager.GetObject("metadata_encoding_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_encoding_002 {
            get {
                object obj = ResourceManager.GetObject("metadata_encoding_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_encoding_003 {
            get {
                object obj = ResourceManager.GetObject("metadata_encoding_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_encoding_004 {
            get {
                object obj = ResourceManager.GetObject("metadata_encoding_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_encoding_005 {
            get {
                object obj = ResourceManager.GetObject("metadata_encoding_005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_encoding_006 {
            get {
                object obj = ResourceManager.GetObject("metadata_encoding_006", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_metaOrigLength_001 {
            get {
                object obj = ResourceManager.GetObject("metadata_metaOrigLength_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_metaOrigLength_002 {
            get {
                object obj = ResourceManager.GetObject("metadata_metaOrigLength_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_padding_001 {
            get {
                object obj = ResourceManager.GetObject("metadata_padding_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_schema_metadata_001 {
            get {
                object obj = ResourceManager.GetObject("metadata_schema_metadata_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_schema_metadata_002 {
            get {
                object obj = ResourceManager.GetObject("metadata_schema_metadata_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_schema_metadata_003 {
            get {
                object obj = ResourceManager.GetObject("metadata_schema_metadata_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_schema_metadata_004 {
            get {
                object obj = ResourceManager.GetObject("metadata_schema_metadata_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_well_formed_001 {
            get {
                object obj = ResourceManager.GetObject("metadata_well_formed_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_well_formed_002 {
            get {
                object obj = ResourceManager.GetObject("metadata_well_formed_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_well_formed_003 {
            get {
                object obj = ResourceManager.GetObject("metadata_well_formed_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] metadata_well_formed_004 {
            get {
                object obj = ResourceManager.GetObject("metadata_well_formed_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tabledata_compression_001 {
            get {
                object obj = ResourceManager.GetObject("tabledata_compression_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tabledata_compression_002 {
            get {
                object obj = ResourceManager.GetObject("tabledata_compression_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tabledata_compression_003 {
            get {
                object obj = ResourceManager.GetObject("tabledata_compression_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tabledata_compression_004 {
            get {
                object obj = ResourceManager.GetObject("tabledata_compression_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tabledata_zlib_001 {
            get {
                object obj = ResourceManager.GetObject("tabledata_zlib_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] valid_001 {
            get {
                object obj = ResourceManager.GetObject("valid_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] valid_002 {
            get {
                object obj = ResourceManager.GetObject("valid_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] valid_003 {
            get {
                object obj = ResourceManager.GetObject("valid_003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] valid_004 {
            get {
                object obj = ResourceManager.GetObject("valid_004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValidHeaderOnly {
            get {
                object obj = ResourceManager.GetObject("ValidHeaderOnly", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
